import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import ReactQueryProviders from "./providers/react-providers";
import { getQueryClient } from "@/lib/query-client";
import { getHomeData } from "@/lib/api/home";
import { Toaster } from "@/components/ui/sonner";
import ReduxProviders from "./providers/redux-provider";


const manrope = Manrope({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  className={`${manrope.variable} font-display antialiased bg-surface text-slate-900`}
      >
        <ReduxProviders>
          <ReactQueryProviders>
            <main className="min-h-[calc(100vh-522px)]">{children}</main>
            <Toaster />
          </ReactQueryProviders>
        </ReduxProviders>
      </body>
    </html>
  );
}
