import type { Metadata } from "next";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { CATEGORIES } from "@/lib/constants";
import { fetchHandler, methods } from "@/lib/fetch-handler";
import { CategoryResponse } from "@/lib/types";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const categoryResponse = await fetchHandler<CategoryResponse>({
    ...CATEGORIES as {
      endpoint: string,
      method: methods,
    }
  });
  
  
  return (
    <div >
      <Header categories={categoryResponse?.data} />
      <div className="container mx-auto px-4 lg:px-0 py-2 sm:py-4 " >
        {children}
      </div>
      <Footer />
    </div>

  );
}
